-- ====================================================================
-- ESQUEMA COMPLETO DE BASE DE DATOS SUPABASE - SGE ARQ-CONST
-- ====================================================================

-- 1. Tabla de Usuarios
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  name VARCHAR(100) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'PROYECTISTA', -- 'ADMIN' o 'PROYECTISTA'
  rate_per_hour NUMERIC(12, 2) DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 2. Tabla de Obras / Proyectos
CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) UNIQUE NOT NULL,
  description TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', -- 'ACTIVE' o 'COMPLETED'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 3. Tabla de Cargas de Horas (Timesheets)
CREATE TABLE IF NOT EXISTS public.timesheets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  work_date DATE NOT NULL DEFAULT CURRENT_DATE,
  start_time VARCHAR(10) DEFAULT '08:00',
  end_time VARCHAR(10) DEFAULT '12:00',
  hours NUMERIC(6, 2) NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 4. Tabla de Gastos y Reembolsos (Expenses)
CREATE TABLE IF NOT EXISTS public.expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  project_id BIGINT REFERENCES projects(id) ON DELETE SET NULL,
  expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
  amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  category VARCHAR(50) NOT NULL DEFAULT 'OFFICE', -- 'OFFICE' o 'PROJECT'
  description TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING', -- 'PENDING' o 'REIMBURSED'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- ====================================================================
-- CONFIGURACIÓN DE RLS Y POLÍTICAS DE ACCESO (DESAPARECE ADVERTENCIAS EN SUPABASE)
-- ====================================================================

-- Habilitar RLS en las 4 tablas
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.timesheets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;

-- Otorgar permisos a los roles de Supabase
GRANT ALL ON TABLE public.users TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.projects TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.timesheets TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.expenses TO anon, authenticated, service_role;

-- Crear Políticas de Acceso Permisivo para el servidor Backend (Express API)
DROP POLICY IF EXISTS "Acceso total users" ON public.users;
CREATE POLICY "Acceso total users" ON public.users FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso total projects" ON public.projects;
CREATE POLICY "Acceso total projects" ON public.projects FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso total timesheets" ON public.timesheets;
CREATE POLICY "Acceso total timesheets" ON public.timesheets FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso total expenses" ON public.expenses;
CREATE POLICY "Acceso total expenses" ON public.expenses FOR ALL USING (true) WITH CHECK (true);
